export default {
  '--theme-bg-primary': '#0a0a0a',
  '--theme-bg-secondary': '#111111',
  '--theme-bg-tertiary': '#1a1a1a',
  '--theme-text-primary': '#00ff41',
  '--theme-text-secondary': '#00cc33',
  '--theme-text-muted': '#00802b',
  '--theme-accent': '#ffb000',
  '--theme-accent-hover': '#ffc940',
  '--theme-border': '#00cc33',
  '--theme-link': '#00ff41',
  '--theme-font-family': '"Courier New", "Consolas", "Monaco", monospace',
  '--theme-font-family-heading': '"Courier New", "Consolas", "Monaco", monospace',
  '--theme-font-size-base': '15px',
  '--theme-font-size-h1': '18px',
  '--theme-font-size-h2': '16px',
  '--theme-line-height': '1.8',
  '--theme-letter-spacing': '0.5px',
  '--theme-font-weight-body': '400',
  '--theme-font-weight-heading': '700',
  '--theme-spacing-xs': '4px',
  '--theme-spacing-sm': '8px',
  '--theme-spacing-md': '16px',
  '--theme-spacing-lg': '24px',
  '--theme-spacing-xl': '32px',
  '--theme-content-max-width': '900px',
  '--theme-sidebar-width': '0px',
  '--theme-border-radius': '0px',
  '--theme-border-width': '1px',
  '--theme-nav-height': '40px',
  '--theme-content-padding': '24px',
  '--theme-shadow': 'none',
  '--theme-transition-speed': '0ms',
};
