export default {
  '--theme-bg-primary': '#ffffff',
  '--theme-bg-secondary': '#f0f0f0',
  '--theme-bg-tertiary': '#e0e0e0',
  '--theme-text-primary': '#000000',
  '--theme-text-secondary': '#333333',
  '--theme-text-muted': '#666666',
  '--theme-accent': '#ff0000',
  '--theme-accent-hover': '#cc0000',
  '--theme-border': '#000000',
  '--theme-link': '#ff0000',
  '--theme-font-family': 'system-ui, -apple-system, "Helvetica Neue", Arial, sans-serif',
  '--theme-font-family-heading': '"Courier New", "Consolas", monospace',
  '--theme-font-size-base': '18px',
  '--theme-font-size-h1': '64px',
  '--theme-font-size-h2': '42px',
  '--theme-line-height': '1.6',
  '--theme-letter-spacing': '0px',
  '--theme-font-weight-body': '400',
  '--theme-font-weight-heading': '900',
  '--theme-spacing-xs': '4px',
  '--theme-spacing-sm': '8px',
  '--theme-spacing-md': '24px',
  '--theme-spacing-lg': '48px',
  '--theme-spacing-xl': '64px',
  '--theme-content-max-width': '1200px',
  '--theme-sidebar-width': '0px',
  '--theme-border-radius': '0px',
  '--theme-border-width': '3px',
  '--theme-nav-height': '60px',
  '--theme-content-padding': '32px',
  '--theme-shadow': 'none',
  '--theme-transition-speed': '0ms',
};
