export default {
  '--theme-bg-primary': '#3a6ea5',
  '--theme-bg-secondary': '#ece9d8',
  '--theme-bg-tertiary': '#d6d2c2',
  '--theme-text-primary': '#000000',
  '--theme-text-secondary': '#444444',
  '--theme-text-muted': '#808080',
  '--theme-accent': '#0054e3',
  '--theme-accent-hover': '#0066ff',
  '--theme-border': '#808080',
  '--theme-link': '#0066cc',
  '--theme-font-family': '"Tahoma", "Segoe UI", sans-serif',
  '--theme-font-family-heading': '"Tahoma", "Segoe UI", sans-serif',
  '--theme-font-size-base': '13px',
  '--theme-font-size-h1': '22px',
  '--theme-font-size-h2': '18px',
  '--theme-line-height': '1.5',
  '--theme-letter-spacing': '0px',
  '--theme-font-weight-body': '400',
  '--theme-font-weight-heading': '700',
  '--theme-spacing-xs': '4px',
  '--theme-spacing-sm': '8px',
  '--theme-spacing-md': '16px',
  '--theme-spacing-lg': '24px',
  '--theme-spacing-xl': '32px',
  '--theme-content-max-width': '1100px',
  '--theme-sidebar-width': '180px',
  '--theme-border-radius': '3px',
  '--theme-border-width': '2px',
  '--theme-nav-height': '34px',
  '--theme-content-padding': '16px',
  '--theme-shadow': '2px 2px 10px rgba(0,0,0,0.3)',
  '--theme-transition-speed': '150ms',
  // XP-specific
  '--xp-blue': '#0a246a',
  '--xp-blue-light': '#0054e3',
  '--xp-luna-gradient-start': '#0997ff',
  '--xp-luna-gradient-end': '#0053ee',
  '--xp-inactive-gradient-start': '#8599b0',
  '--xp-inactive-gradient-end': '#6181a3',
  '--xp-button-face': '#ece9d8',
  '--xp-window-bg': '#ece9d8',
  '--xp-text-color': '#000000',
  '--xp-textarea-bg': '#ffffff',
};
