export default {
  '--theme-bg-primary': '#0d0221',
  '--theme-bg-secondary': '#1a0533',
  '--theme-bg-tertiary': '#240845',
  '--theme-text-primary': '#e0d6ff',
  '--theme-text-secondary': '#b8a9e0',
  '--theme-text-muted': '#7a6b99',
  '--theme-accent': '#00fff5',
  '--theme-accent-hover': '#ff6eb4',
  '--theme-border': '#00fff5',
  '--theme-link': '#00fff5',
  '--theme-font-family': 'system-ui, -apple-system, "Segoe UI", Roboto, sans-serif',
  '--theme-font-family-heading': 'system-ui, -apple-system, "Segoe UI", Roboto, sans-serif',
  '--theme-font-size-base': '16px',
  '--theme-font-size-h1': '42px',
  '--theme-font-size-h2': '28px',
  '--theme-line-height': '1.7',
  '--theme-letter-spacing': '0.5px',
  '--theme-font-weight-body': '400',
  '--theme-font-weight-heading': '700',
  '--theme-spacing-xs': '6px',
  '--theme-spacing-sm': '12px',
  '--theme-spacing-md': '24px',
  '--theme-spacing-lg': '40px',
  '--theme-spacing-xl': '64px',
  '--theme-content-max-width': '900px',
  '--theme-sidebar-width': '0px',
  '--theme-border-radius': '8px',
  '--theme-border-width': '1px',
  '--theme-nav-height': '56px',
  '--theme-content-padding': '32px',
  '--theme-shadow': '0 0 20px rgba(0, 255, 245, 0.15)',
  '--theme-transition-speed': '200ms',
  // Synthwave-specific
  '--synthwave-cyan': '#00fff5',
  '--synthwave-magenta': '#ff2975',
  '--synthwave-hot-pink': '#ff6eb4',
  '--synthwave-purple': '#b026ff',
  '--synthwave-yellow': '#ffd319',
};
