export default {
  '--theme-bg-primary': '#f5f0e8',
  '--theme-bg-secondary': '#ebe6de',
  '--theme-bg-tertiary': '#e0dbd3',
  '--theme-text-primary': '#1a1a1a',
  '--theme-text-secondary': '#4a4a4a',
  '--theme-text-muted': '#6b6b6b',
  '--theme-accent': '#8b0000',
  '--theme-accent-hover': '#a50000',
  '--theme-border': '#c0b8a8',
  '--theme-link': '#8b0000',
  '--theme-font-family': 'Georgia, "Times New Roman", "Palatino Linotype", Palatino, serif',
  '--theme-font-family-heading': 'Georgia, "Times New Roman", "Palatino Linotype", Palatino, serif',
  '--theme-font-size-base': '17px',
  '--theme-font-size-h1': '36px',
  '--theme-font-size-h2': '24px',
  '--theme-line-height': '1.7',
  '--theme-letter-spacing': '0px',
  '--theme-font-weight-body': '400',
  '--theme-font-weight-heading': '700',
  '--theme-spacing-xs': '4px',
  '--theme-spacing-sm': '8px',
  '--theme-spacing-md': '16px',
  '--theme-spacing-lg': '24px',
  '--theme-spacing-xl': '40px',
  '--theme-content-max-width': '960px',
  '--theme-sidebar-width': '0px',
  '--theme-border-radius': '0px',
  '--theme-border-width': '1px',
  '--theme-nav-height': '40px',
  '--theme-content-padding': '24px',
  '--theme-shadow': 'none',
  '--theme-transition-speed': '200ms',
  // Newspaper-specific tokens
  '--newspaper-bg': '#f5f0e8',
  '--newspaper-text': '#1a1a1a',
  '--newspaper-secondary': '#4a4a4a',
  '--newspaper-accent': '#8b0000',
  '--newspaper-rule': '#1a1a1a',
  '--newspaper-rule-light': '#c0b8a8',
  '--newspaper-masthead-size': '3.2rem',
};
