export default {
  '--theme-bg-primary': '#fafaf9',
  '--theme-bg-secondary': '#f5f5f4',
  '--theme-bg-tertiary': '#e7e5e4',
  '--theme-text-primary': '#1a1a1a',
  '--theme-text-secondary': '#6b6b6b',
  '--theme-text-muted': '#a3a3a3',
  '--theme-accent': '#2d2d2d',
  '--theme-accent-hover': '#1a1a1a',
  '--theme-border': '#e5e5e5',
  '--theme-link': '#8b4513',
  '--theme-font-family': '"Georgia", "Times New Roman", serif',
  '--theme-font-family-heading': '"Georgia", "Times New Roman", serif',
  '--theme-font-size-base': '17px',
  '--theme-font-size-h1': '24px',
  '--theme-font-size-h2': '20px',
  '--theme-line-height': '1.8',
  '--theme-letter-spacing': '0.2px',
  '--theme-font-weight-body': '400',
  '--theme-font-weight-heading': '400',
  '--theme-spacing-xs': '8px',
  '--theme-spacing-sm': '16px',
  '--theme-spacing-md': '32px',
  '--theme-spacing-lg': '48px',
  '--theme-spacing-xl': '64px',
  '--theme-content-max-width': '640px',
  '--theme-sidebar-width': '0px',
  '--theme-border-radius': '0px',
  '--theme-border-width': '1px',
  '--theme-nav-height': '48px',
  '--theme-content-padding': '24px',
  '--theme-shadow': 'none',
  '--theme-transition-speed': '300ms',
};
